require "impatient"
require "ilhan.settings"
require "ilhan.keymappings"
require "ilhan.plugins"
require "ilhan.colorscheme"
require "ilhan.tabline"
require "ilhan.completion"
require "ilhan.globals"
require "ilhan.lsp"
require "ilhan.tree"
require "ilhan.treesitter"
-- require "ilhan.colorizer"
